### ISSUE TITLE
Nudge towards bandcamp where possible?

### ISSUE THREAD

**Issue by joho** [pat/support-act#4]
Was thinking of seeing if it's possible to match artist/album against bandcamp and nudging people towards purchasing on that platform where available.

Especially with https://isitbandcampfriday.com/ where artists get 100% of the revenue from a sale.

Thoughts?

**Comment by pat** [comment]
I'd love to point people towards places to buy music where possible - and especially places like Bandcamp which are better at supporting artists. So yes, definitely keen for this!

Challenges to work through:

* Do we crowdsource Bandcamp matches, or use an API/crawler to get pretty accurate matches?
* Where else can we direct people to buy from if an artist/band isn't on Bandcamp?
* How best to normalise the artists table - as currently Last.fm and Spotify values are separated (I avoided wrangling this because some bands have the same name, though it is very rare) 🤔

**Comment by joho** [comment]
I was getting bad flashbacks to the goodfilms days. Music and movies are such difficult data sets to work with, especially if you want to link to online store fronts. At least books have ISBNs.

That said, looks like [musicbrainz](https://musicbrainz.org/) could be a go-er. It has an API, and it links to purchase locations: [here is an example release](https://musicbrainz.org/release/75d32ed2-6136-4ddc-a5f7-72cb61cd4fe4).

**Comment by pat** [comment]
Okay, dashboard and emails will now display links from MusicBrainz if that has any information. It's not super-pretty, but I'll do for now.

There seems there's a lot of holes in the MB data though, so I'll look into Odesli soon for additional links. Granted, I will definitely need an API key for their service, because otherwise they rate limit at 10 requests per minute 😅

**Comment by pat** [comment]
Okay, I've added in Odesli as well (and they kindly gave me an API key for a better rate limit), but there's still a tonne of missing links. Also, Odesli doesn't support Bandcamp (who I've emailed to see if they have any undocumented APIs for finding artists/albums).

So: plenty of room for improvement, but this is a solid enough start that I'm happy to close this issue for now :)
